### ISSUE TITLE
Can No Longer Play - Always Asks to Log Out

### ISSUE THREAD

**Issue by WanderingJesusFreak** [mtaheij/PoGo-UWP#15] opened 2017-02-15 14:23 UTC
Device info
------------------
- Phone type: Lumia 950 XL
- App version: 1.2.4

Steps to reproduce
----------------
Start the game or try to log back in

Actual behavior
-----------------
When starting the game, it says Logging In and then Getting Gps Data. It gets through these two phases and the comes to the downloading user data part. It then says the app is unstable and continues to give that prompt unless I select Yes. It then gives it to me one or two more times and I select Yes both times. I am then brought to the login screen. If I try to log.on again it goes through the whole process again. 

Expected behavior
---------------

Other information
---------------
I was reading on the pokemongodev Reddit that Niantic changed something with their login process.

**Comment by andremvm** [comment] 2017-02-15 15:09
Probably they are changing the API again. I have read just now that they confirmed that this week the 2nd gen pokemons are coming (80 so far), and that new items will come, and together with it, changes in the behaviour of the pokemons you are trying to catch! So maybe we will have to wait some time until we can play again...

**Comment by mtaheij** [comment] 2017-02-15 18:45
Indeed, yesterday evening (CET), the requirements for the initial request after login changed. Some API's were prepared for that, but the one we use, wasn't.
We are looking for a fix.
In the mean time, there is a new version of the official app announced, that will introduce 2nd gen pokémons. As far as I'm aware, these two are not directly connected, so if we fix the first, we might need to do more for the new version, especially when the API changes again.

**Comment by DarkLegend481** [comment] 2017-02-17 02:49
When does the next update come out with the login fix? Or 2nd Gen (full)?

**Comment by WanderingJesusFreak** [comment] 2017-02-17 13:05
I think we all know they are working hard and for free. Also, they are not in control of the API portion of the project. You may not realize it, but "when" questions for a project like this are usually unhelpful and somewhat frustrating to the developers.

**Comment by BadiBasso** [comment] 2017-02-17 20:44
API is not an issue here. Update to newest proto/API is just waiting to be imported to PoGO-UWP as soon as the login problem is fixed.
PoGo-UWP is already Gen2 compatible at most parts: assets are there for pokedex and pokemon inventory. currently missing are some new item icons and descripitions, work flow for evolution stones and some other minor things, which are quite easy/quick to implement.

**Comment by DarkLegend481** [comment] 2017-02-17 21:21
I'll get the icons and the descriptions of the items ... Will be in UI Update issue

**Comment by BadiBasso** [comment] 2017-02-17 21:40
@DarkLegend481 Thanks. That leaves me and @mtaheij banging our heads to the wall with the login issue :)

**Comment by mtaheij** [comment] 2017-02-18 00:22
Done! We are up and running again.
Code is already available, for a release version, you'll have to wait some more.

**Comment by andremvm** [comment] 2017-02-18 09:29
Many thanks! This time I was able to update it directly from the installed app (in the previous release I was always getting an error and had to re-install it freshly) and now it is running... :)

**Comment by andremvm** [comment] 2017-02-18 18:00
Well, didn't manage to visit a Gym yet (probably will do it later today when I go out again), but already have some feedback to give, which might be helpful to others:

At first, every time I tried to catch a 2nd gen pokemon, the app crashed: either the pokeballs were not being launched or they would be launched to infinity and beyond, and then because I failed the catch the pokeball button would disappear and I had no choice to restart the app.
Eventually, my account increased to level 19 (I caught a few 1st gen pokemon and visited some pokestops) and then everything changed. Now the 2nd gen pokemons are as easy to catch as the 1st gen ones, and the pokeball "bug" is gone.
Now, however, there is a small bug which I guess is simply something you didn't implement yet: whenever I select a 2nd gen pokemon, it says that I only need 1 berry to evolve it (which isn't true, because if I press it to evolve it does nothing)...

Cheers and thanks again for the great work!

**Comment by ntaheij** [comment] 2017-02-18 21:29
@andremvm The new generation 2 pokemons aren't returned with the download settings request. So each pokemon that appears the first time, will have evolve requirements sent with it.
We did not yet discover how. We're trying to fix it.

**Comment by DarkLegend481** [comment] 2017-02-19 01:38
I got a Tododile and a Sunkern, and the app don't crashes...
(Eu peguei um Totodile e uma Sunkern, e o app não deu crash...)

**Comment by ntaheij** [comment] 2017-02-19 08:50
So far as i played (i catched a lot of gen 2 pokemons), within 3 hours, my app crashed one time.

**Comment by BadiBasso** [comment] 2017-02-19 09:22
PoGo downloads same static settings and caches them for a month. Evenif  api changes or app updates they are not reloaded.
Removing and reinstalling clears the cache.

**Comment by andremvm** [comment] 2017-02-19 13:06
Anyway now I only have crashes when I use one of the new berries... Most of the time after I use it, when I have the chance to throw the pokeball again, the pokeball will simply not move! I have to quit from catching that pokemon, then select it again on the map and start all over again.

Regarding the evolutions, I was already able to evolve one of the new pokemons when it reached the 25 berries (Sentret to Furret), so it seems that even the requirements are not shown properly, when we do reach the amount of berries we need it will allow the evolution!

**Comment by BadiBasso** [comment] 2017-02-19 14:58
Niantic has changed the code when using berries, so atm only Razz Berry seems to work. Using new berries has no effect , buy luckily their amount is not decreased; at least what I have noticed.
I have noticed the same hung problem in capture too.

About evolving: can you send a screenshot of wrong candy value?.

**Comment by mtaheij** [comment] 2017-02-19 16:27
The game settings are cached indeed. When the ForceRefresh parameter for GameClient.UpdateItemTemplates is set to true, the settings will be renewed.
Next version will have a variable in version.json to let the app force-update settings.

**Comment by andremvm** [comment] 2017-02-19 18:40
@BadiBasso Here is a screenshot with the evolving issue.. Not really a big problem, I just have to try from time to time to check if the candies I have are enough or not!

Regarding the gyms, I was able now to chose a team (although the app crashed immediately afterwards, restarted it and has been running fine) but not able to deploy pokemons there yet because they are full!

Another thing. From time to time a window pops up with a capcha for proving I am not a robot. I have to check it, then solve some images (like select all that have a street sign,...), it says that it was sucessful, but then all pokestops and pokemon disappear for like 1 minute. Is it normal?

![wp_ss_20170219_0002](https://cloud.githubusercontent.com/assets/25388446/23105197/3bf536e2-f6db-11e6-8db0-6ecb80a4da2e.png)
![wp_ss_20170219_0003](https://cloud.githubusercontent.com/assets/25388446/23105195/3bf2b8f4-f6db-11e6-86ec-dd272cb08d4d.png)
![wp_ss_20170219_0004](https://cloud.githubusercontent.com/assets/25388446/23105196/3bf41f46-f6db-11e6-8e13-0adbd8c03a5d.png)

**Comment by andremvm** [comment] 2017-02-22 21:05
Is it just me that cannot login again (i.e., was my account finally banned) or is it general?

**Comment by WanderingJesusFreak** [comment] 2017-02-25 01:40
This ended up being a problem on PTC servers. I had the same problem but it worked fine by the end of the day

**Closed** 2017-02-25 09:58 UTC

**Comment by mtaheij** [comment] 2017-03-02 07:55
Yes, the app is working currently. If you still have problems, try logging out, disable the checkmark 'remember me', quitting the app and logging in again.
Still no luck? Uninstall and install might help.
