### ISSUE TITLE
Several minor bugs

### ISSUE THREAD

**Issue by Dragoncat4** [mtaheij/PoGo-UWP#29] opened 2017-03-07 21:15 UTC
I'll just list several minor bugs I've encountered when playing, just to let you know. If they're known - please just close this issue.

1) Evolution of Sunken (the seed monster...) requires by default sunstone, however, in the application it's evolution is available as normal evolution. It might potentially cause some issues.
2) Using berry returns always to pokeball instead of the previously selected ball.
3) The range of detected pokemons in just too high - in my case it just disables for me to use the tracker since half of listed pokestops are unknown to me. The list of pokemons should be ordered somehow by the location to the pokestop.
4) The information about strength and other parameters is available. There was an episode when people who wanted to know of those parameters were banned due to usage of the application that enabled it. However, on the other hand, percentages in same line of those parameters can be used to easily determine the outcome of assessment (iirc >80% wonder, >60% caught interest, >40 average and lower - not much headway in battle).

I'll add more as soon as I recall more of them.

**Comment by ntaheij** [comment] 2017-03-08 11:55
At point 3. the distance to the pokemon is somehow, so far as i know, 200

**Comment by DarkLegend481** [comment] 2017-03-12 23:29
5. Some Pokémon from Kanto that haves evolution from Johto (Ex: Porygon > Porygon2) doesn't have a evolve button.

**Comment by Dragoncat4** [comment] 2017-03-13 06:30
Those are evolutions which require the evolutionary item. I assumed they are not yet implemented and therefore did not include this particle issue in the list.

**Comment by BadiBasso** [comment] 2017-03-15 16:39
Niantic has changed code regarding evolutions and evolution lines. Currently PoGo does not support using stones or some evolutions across Kanto-Johto. Trying to evolve without a stone just throws an error, nothing serious.

**Comment by BadiBasso** [comment] 2017-03-15 16:48
IV values are obtainable without any hacks, they are part of pokemon's attributes returned from the server. Official client does not show them directly but uses them in appraisals. They are visible as of now since appraisal is not yet implemented in PoGo.

**Comment by BadiBasso** [comment] 2017-03-19 12:40
@mtaheij Anyone working on new evolutions? I might as well focus on that now that using new Pogolib API seems to be way more stable and reliable.

**Comment by mtaheij** [comment] 2017-03-19 13:05
No, I'm not. I am working on stability improvements and gym battling.

**Comment by andremvm** [comment] 2017-03-20 17:29
I don't know if this is happening to somebody else, but lately I noticed a new "bug": when an egg hatches I get no notification, neither that it hatched nor which was the pokemon I got!

**Comment by Dragoncat4** [comment] 2017-03-20 19:02
I noticed that today as well. No notification on egg hatching.
Also very long GPS localising and often crashes on pokestops/pokemons fight.

**Comment by andremvm** [comment] 2017-03-20 19:04
I have not tried the pokemon fights yet. With the pokestops simply sometimes even though it is shown as open, it keeps saying that I am too far away, but I though that was an hashing service problem! I do not have any problem with the GPS, it localizes my position quite fast, in a few seconds...

**Comment by mtaheij** [comment] 2017-03-20 19:08
Egg hatching will be repaired in the next update. I've done some changes over the last weekend to solve this.

**Comment by andremvm** [comment] 2017-03-20 19:08
Great! :)

**Comment by andremvm** [comment] 2017-03-28 07:33
I can confirm that the egg hatching issue is fixed in this new version, thanks!

**Comment by RSikkel** [comment] 2017-03-31 09:02
As compared to the official app, the radius in which you can see the pokemon that are close to you is way higher in pogo uwp. The radius for being able to activate a pokestop is somewhat smaller though.

**Comment by mtaheij** [comment] 2017-03-31 09:27
The request to retrieve pokemon on the map is the same as in the original app, otherwise, there would be many more captchas.
What could be the case is that the official app loads all available pokemon, but shows only a subset of them on the screen, only the ones that are in a certain range. This could be because when you move just a little bit, there is no need to load new data as there are pokemons available for the new area in the previous response.
I think we're not directly in trouble when showing these on the screen. Capturing them from a too high distance might be.

**Comment by RSikkel** [comment] 2017-03-31 09:53
Another difference as compared to the original app, you accumulate way fewer km's walked (around 1/4th i would say) in the original app. I'm just sending all the differences I find in the hope of being able to have as little pogo uwp players banned in the future :)

**Comment by andremvm** [comment] 2017-03-31 12:24
That issue with the km doesn't make too much sense to me... Could it simply be that the GPS in your windows phone is less precise and makes your character move randomly more often?

**Comment by mtaheij** [comment] 2017-03-31 12:44
I think this has to do with the POGOLib implementation of the API. 
I have a technical explanation available, but don't want to give away too much information to any Niantic developer that might be reading here ;-)
The reason for not receiving so many captcha's anymore is in the same area - I think.

**Comment by ntaheij** [comment] 2017-04-01 19:10
Solved. If not please reopen issue

**Closed by ntaheij** 2017-04-01 19:10 UTC
